'use strict';

const { TRANSCRIPT_SCHEMA_VERSION, SEGMENT_STATUS } = require('../../shared/constants');

function escapeHtml(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function pad(n, width = 2) {
  return String(n).padStart(width, '0');
}

/** Format seconds as HH:MM:SS,mmm for SRT. */
function formatSrtTime(seconds) {
  const s = Math.max(0, Number(seconds) || 0);
  const ms = Math.round((s % 1) * 1000);
  const total = Math.floor(s);
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const sec = total % 60;
  return `${pad(h)}:${pad(m)}:${pad(sec)},${pad(ms, 3)}`;
}

/** Format seconds as HH:MM:SS.mmm for display. */
function formatClock(seconds) {
  const s = Math.max(0, Number(seconds) || 0);
  const ms = Math.round((s % 1) * 1000);
  const total = Math.floor(s);
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const sec = total % 60;
  return `${pad(h)}:${pad(m)}:${pad(sec)}.${pad(ms, 3)}`;
}

function buildMeta({ caseRecord, evidence, transcript, segments, language, modelId, engine }) {
  const humanEdited = segments.filter((s) => s.status !== SEGMENT_STATUS.AUTOMATIC).length;
  return {
    schema_version: TRANSCRIPT_SCHEMA_VERSION,
    generated_at: new Date().toISOString(),
    case_id: caseRecord ? caseRecord.case_id : null,
    case_title: caseRecord ? caseRecord.title : null,
    case_notes: caseRecord ? caseRecord.notes : null,
    evidence_id: evidence ? evidence.evidence_id : null,
    evidence_name: evidence ? evidence.original_name : null,
    evidence_sha256: evidence ? evidence.sha256 : null,
    evidence_duration_seconds: evidence ? evidence.duration_seconds : null,
    language: language || 'tr',
    engine: engine || null,
    model_id: modelId || null,
    segment_count: segments.length,
    human_reviewed_segment_count: humanEdited,
    transcript_status_note:
      'Segments marked AUTOMATIC are machine output and are not expert opinion. REVIEWED/EDITED/VERIFIED reflect human action.',
    tool_note:
      'Generated by Forensic Transcriber, a transcription and review aid for 56.12 audio transcription workflows. It does not constitute a forensic opinion, legal assessment, speaker identification, or authenticity determination.',
  };
}

function toJson({ caseRecord, evidence, transcript, segments, language, modelId, engine }) {
  const meta = buildMeta({ caseRecord, evidence, transcript, segments, language, modelId, engine });
  return JSON.stringify(
    {
      ...meta,
      segments: segments.map((s) => ({
        segment_id: s.segment_id,
        start: s.start,
        end: s.end,
        speaker: s.speaker,
        text: s.text,
        // The automatic (machine) text is exported alongside the current text
        // whenever it differs, so an edited segment never hides what the engine
        // originally produced.
        original_text: s.original_text !== undefined && s.original_text !== null && s.original_text !== s.text
          ? s.original_text
          : undefined,
        status: s.status,
        confidence: s.confidence ?? null,
        words: s.words ?? undefined,
      })),
    },
    null,
    2
  );
}

function toTxt({ caseRecord, evidence, segments, language, modelId, engine }) {
  const meta = buildMeta({ caseRecord, evidence, transcript: null, segments, language, modelId, engine });
  const lines = [];
  lines.push('FORENSIC TRANSCRIBER — TRANSCRIPT (working draft)');
  lines.push('='.repeat(60));
  if (caseRecord) {
    lines.push(`Case: ${caseRecord.case_id} — ${caseRecord.title}`);
    if (caseRecord.notes) lines.push(`Notes: ${caseRecord.notes}`);
  }
  if (evidence) {
    lines.push(`Evidence: ${evidence.original_name}`);
    lines.push(`SHA-256: ${evidence.sha256}`);
    if (evidence.duration_seconds != null) {
      lines.push(`Duration: ${formatClock(evidence.duration_seconds)}`);
    }
  }
  lines.push(`Language: ${language || 'tr'}   Engine: ${engine || 'n/a'}   Model: ${modelId || 'n/a'}`);
  lines.push(`Generated: ${meta.generated_at}`);
  lines.push('');
  lines.push('AUTOMATIC segments are machine output, not expert opinion.');
  lines.push('-'.repeat(60));
  for (const s of segments) {
    lines.push(`[${formatClock(s.start)} – ${formatClock(s.end)}] ${s.speaker} (${s.status})`);
    lines.push(s.text);
    lines.push('');
  }
  lines.push('-'.repeat(60));
  lines.push(meta.tool_note);
  return lines.join('\n');
}

function toSrt({ segments }) {
  const blocks = [];
  segments.forEach((s, i) => {
    const statusSuffix = s.status === SEGMENT_STATUS.AUTOMATIC ? '' : ` {${s.status}}`;
    blocks.push(
      [
        String(i + 1),
        `${formatSrtTime(s.start)} --> ${formatSrtTime(s.end)}`,
        `[${s.speaker}] ${s.text}${statusSuffix}`,
      ].join('\n')
    );
  });
  return `${blocks.join('\n\n')}\n`;
}

function toHtml({ caseRecord, evidence, segments, language, modelId, engine }) {
  const meta = buildMeta({ caseRecord, evidence, transcript: null, segments, language, modelId, engine });
  const rows = segments
    .map((s) => {
      const cls = s.status.toLowerCase();
      const conf = s.confidence == null ? '' : `<span class="conf">conf ${s.confidence.toFixed(2)}</span>`;
      return `      <div class="seg ${cls}" data-start="${s.start}" data-end="${s.end}" data-id="${escapeHtml(s.segment_id)}">
        <div class="meta"><button class="ts" data-start="${s.start}">${formatClock(s.start)}</button><span class="sep">–</span><span class="ts">${formatClock(s.end)}</span><span class="speaker">${escapeHtml(s.speaker)}</span><span class="status">${escapeHtml(s.status)}</span>${conf}</div>
        <div class="text">${escapeHtml(s.text)}</div>
      </div>`;
    })
    .join('\n');

  const header = [
    caseRecord ? `Case ${escapeHtml(caseRecord.case_id)} — ${escapeHtml(caseRecord.title)}` : '',
    evidence ? `Evidence ${escapeHtml(evidence.original_name)}` : '',
    evidence ? `SHA-256 ${escapeHtml(evidence.sha256)}` : '',
    `Language ${escapeHtml(language || 'tr')} · Engine ${escapeHtml(engine || 'n/a')} · Model ${escapeHtml(modelId || 'n/a')}`,
  ]
    .filter(Boolean)
    .map((l) => `      <p>${l}</p>`)
    .join('\n');

  return `<!doctype html>
<html lang="tr">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Forensic Transcriber — Transcript</title>
  <style>
    :root { color-scheme: light; }
    body { font-family: -apple-system, "Segoe UI", Roboto, Arial, sans-serif; margin: 0; background: #f4f5f7; color: #1b1f24; }
    header { padding: 24px 32px; background: #10151c; color: #e8eef6; }
    header h1 { margin: 0 0 8px; font-size: 20px; }
    header p { margin: 2px 0; font-size: 13px; color: #9fb0c3; word-break: break-all; }
    .notice { padding: 12px 32px; background: #fff5e0; color: #6b4e00; font-size: 13px; border-bottom: 1px solid #f0dca6; }
    main { padding: 16px 32px 48px; max-width: 960px; }
    .seg { background: #fff; border: 1px solid #e2e6ea; border-left: 4px solid #b7c0cc; border-radius: 8px; padding: 12px 14px; margin: 10px 0; }
    .seg.automatic { border-left-color: #b7c0cc; }
    .seg.reviewed { border-left-color: #2f7de1; }
    .seg.edited { border-left-color: #d98a00; }
    .seg.verified { border-left-color: #1f9d55; }
    .meta { display: flex; gap: 10px; align-items: center; font-size: 12px; color: #5a6673; margin-bottom: 6px; flex-wrap: wrap; }
    .ts { background: none; border: none; color: #2f7de1; font: inherit; cursor: pointer; padding: 0; }
    .speaker { font-weight: 600; color: #333c46; }
    .status { text-transform: uppercase; letter-spacing: .04em; font-size: 11px; background: #eef1f4; border-radius: 4px; padding: 1px 6px; }
    .conf { color: #8a949e; }
    .text { font-size: 15px; line-height: 1.5; white-space: pre-wrap; }
    footer { padding: 16px 32px; font-size: 12px; color: #6b7683; border-top: 1px solid #e2e6ea; }
    @media print { body { background: #fff; } .seg { break-inside: avoid; } header { background: #fff; color: #000; border-bottom: 1px solid #ccc; } header p { color: #444; } }
  </style>
</head>
<body>
  <header>
    <h1>Forensic Transcriber — Transcript (working draft)</h1>
${header}
  </header>
  <div class="notice">AUTOMATIC segments are machine output and are not expert opinion. REVIEWED / EDITED / VERIFIED reflect human action.</div>
  <main>
${rows}
  </main>
  <footer>${escapeHtml(meta.tool_note)} Generated ${escapeHtml(meta.generated_at)}.</footer>
</body>
</html>
`;
}

module.exports = {
  toJson,
  toTxt,
  toSrt,
  toHtml,
  buildMeta,
  formatSrtTime,
  formatClock,
  escapeHtml,
};
